export const bestchange =
    {
        "rates": {
            "item": [
                {
                    "FROM": "SBERRUB",
                    "TO": "BTC",
                    "FROMFEE": 0,
                    "TOFEE": 0.00018655,
                    "IN": 183331037.35,
                    "OUT": 100,
                    "AMOUNT": 0.009276,
                    "MINAMOUNT": 4000,
                    "MAXAMOUNT": 16804.13,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BTC",
                    "TO": "SBERRUB",
                    "FROMFEE": 0.00001,
                    "TOFEE": 0,
                    "IN": 20,
                    "OUT": 32615090.44,
                    "AMOUNT": 100000,
                    "MINAMOUNT": 0.00300505,
                    "MAXAMOUNT": 0.06010101,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBERRUB",
                    "TO": "USDTTRC20",
                    "FROMFEE": 0,
                    "TOFEE": 2.756705,
                    "IN": 79441262.15,
                    "OUT": 1000000,
                    "AMOUNT": 391.82054738,
                    "MINAMOUNT": 23322,
                    "MAXAMOUNT": 30612.43,
                    "PARAM": "manual"
                },
                {
                    "FROM": "USDTTRC20",
                    "TO": "SBERRUB",
                    "FROMFEE": 4.694508,
                    "TOFEE": 0,
                    "IN": 1000000,
                    "OUT": 75812009.12,
                    "AMOUNT": 100000,
                    "MINAMOUNT": 300,
                    "MAXAMOUNT": 1292.80309445,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBERRUB",
                    "TO": "LTC",
                    "FROMFEE": 0,
                    "TOFEE": 0.0000332,
                    "IN": 7027.07,
                    "OUT": 1,
                    "AMOUNT": 2.42003546,
                    "MINAMOUNT": 4000,
                    "MAXAMOUNT": 16804.13,
                    "PARAM": "manual"
                },
                {
                    "FROM": "LTC",
                    "TO": "SBERRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 6250.68,
                    "AMOUNT": 100000,
                    "MINAMOUNT": 0.78399444,
                    "MAXAMOUNT": 15.6798888,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBERRUB",
                    "TO": "DASH",
                    "FROMFEE": 0,
                    "TOFEE": 0.00000372,
                    "IN": 5010.43,
                    "OUT": 1,
                    "AMOUNT": 3.39407096,
                    "MINAMOUNT": 4000,
                    "MAXAMOUNT": 16804.13,
                    "PARAM": "manual"
                },
                {
                    "FROM": "DASH",
                    "TO": "SBERRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 4456.85,
                    "AMOUNT": 100000,
                    "MINAMOUNT": 1.09954288,
                    "MAXAMOUNT": 21.99085758,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBERRUB",
                    "TO": "ZEC",
                    "FROMFEE": 0,
                    "TOFEE": 0.00003,
                    "IN": 3087.29,
                    "OUT": 1,
                    "AMOUNT": 5.50831112,
                    "MINAMOUNT": 4000,
                    "MAXAMOUNT": 16804.13,
                    "PARAM": "manual"
                },
                {
                    "FROM": "ZEC",
                    "TO": "SBERRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 2746.19,
                    "AMOUNT": 100000,
                    "MINAMOUNT": 1.78447191,
                    "MAXAMOUNT": 35.68943811,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBERRUB",
                    "TO": "ETH",
                    "FROMFEE": 0,
                    "TOFEE": 0.00068333,
                    "IN": 128210.72,
                    "OUT": 1,
                    "AMOUNT": 0.13263929,
                    "MINAMOUNT": 4000,
                    "MAXAMOUNT": 16804.13,
                    "PARAM": "manual"
                },
                {
                    "FROM": "ETH",
                    "TO": "SBERRUB",
                    "FROMFEE": 0.00124242,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 114045.18,
                    "AMOUNT": 100000,
                    "MINAMOUNT": 0.04296981,
                    "MAXAMOUNT": 0.8593962,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBERRUB",
                    "TO": "XMR",
                    "FROMFEE": 0,
                    "TOFEE": 0.0001426,
                    "IN": 12404.17,
                    "OUT": 1,
                    "AMOUNT": 1.37097191,
                    "MINAMOUNT": 4000,
                    "MAXAMOUNT": 16804.13,
                    "PARAM": "manual"
                },
                {
                    "FROM": "XMR",
                    "TO": "SBERRUB",
                    "FROMFEE": 0.0002139,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 11033.68,
                    "AMOUNT": 100000,
                    "MINAMOUNT": 0.44413992,
                    "MAXAMOUNT": 8.88279837,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBERRUB",
                    "TO": "BNBBEP20",
                    "FROMFEE": 0,
                    "TOFEE": 0.000105,
                    "IN": 23440.7,
                    "OUT": 1,
                    "AMOUNT": 0.72548068,
                    "MINAMOUNT": 4000,
                    "MAXAMOUNT": 16804.13,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BNBBEP20",
                    "TO": "SBERRUB",
                    "FROMFEE": 0.0001575,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 20850.82,
                    "AMOUNT": 100000,
                    "MINAMOUNT": 0.23502665,
                    "MAXAMOUNT": 4.70053291,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBERRUB",
                    "TO": "DOGE",
                    "FROMFEE": 0,
                    "TOFEE": 0.04104,
                    "IN": 6.04,
                    "OUT": 1,
                    "AMOUNT": 2810.90785891,
                    "MINAMOUNT": 4000,
                    "MAXAMOUNT": 16804.13,
                    "PARAM": "manual"
                },
                {
                    "FROM": "DOGE",
                    "TO": "SBERRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 5.38,
                    "AMOUNT": 100000,
                    "MINAMOUNT": 910.62142142,
                    "MAXAMOUNT": 18212.42842834,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBERRUB",
                    "TO": "TRX",
                    "FROMFEE": 0,
                    "TOFEE": 1.5,
                    "IN": 5.46,
                    "OUT": 1,
                    "AMOUNT": 3112.75031163,
                    "MINAMOUNT": 4000,
                    "MAXAMOUNT": 16804.13,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TRX",
                    "TO": "SBERRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 4.85,
                    "AMOUNT": 100000,
                    "MINAMOUNT": 1008.40627141,
                    "MAXAMOUNT": 20168.12542827,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBERRUB",
                    "TO": "BUSD",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 82.35,
                    "OUT": 1,
                    "AMOUNT": 377.97347287,
                    "MINAMOUNT": 23322,
                    "MAXAMOUNT": 30612.43,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BUSD",
                    "TO": "SBERRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 72.9,
                    "AMOUNT": 100000,
                    "MINAMOUNT": 300,
                    "MAXAMOUNT": 1344.31423365,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TCSBRUB",
                    "TO": "BTC",
                    "FROMFEE": 0,
                    "TOFEE": 0.00018655,
                    "IN": 185142608.87,
                    "OUT": 100,
                    "AMOUNT": 0.17108912,
                    "MINAMOUNT": 5000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BTC",
                    "TO": "TCSBRUB",
                    "FROMFEE": 0.00001,
                    "TOFEE": 0,
                    "IN": 20,
                    "OUT": 32382149.28,
                    "AMOUNT": 200000,
                    "MINAMOUNT": 0.0060101,
                    "MAXAMOUNT": 0.12020203,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TCSBRUB",
                    "TO": "USDTTRC20",
                    "FROMFEE": 0,
                    "TOFEE": 2.756705,
                    "IN": 79847531.39,
                    "OUT": 1000000,
                    "AMOUNT": 3967.04642468,
                    "MINAMOUNT": 23322,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "USDTTRC20",
                    "TO": "TCSBRUB",
                    "FROMFEE": 4.694508,
                    "TOFEE": 0,
                    "IN": 1000000,
                    "OUT": 75270550.02,
                    "AMOUNT": 200000,
                    "MINAMOUNT": 300,
                    "MAXAMOUNT": 2585.60618891,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TCSBRUB",
                    "TO": "LTC",
                    "FROMFEE": 0,
                    "TOFEE": 0.0000332,
                    "IN": 7096.51,
                    "OUT": 1,
                    "AMOUNT": 44.63582624,
                    "MINAMOUNT": 5000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "LTC",
                    "TO": "TCSBRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 6206.03,
                    "AMOUNT": 200000,
                    "MINAMOUNT": 1.56798888,
                    "MAXAMOUNT": 31.3597776,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TCSBRUB",
                    "TO": "DASH",
                    "FROMFEE": 0,
                    "TOFEE": 0.00000372,
                    "IN": 5059.94,
                    "OUT": 1,
                    "AMOUNT": 62.60121551,
                    "MINAMOUNT": 5000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "DASH",
                    "TO": "TCSBRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 4425.02,
                    "AMOUNT": 200000,
                    "MINAMOUNT": 2.19908576,
                    "MAXAMOUNT": 43.98171516,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TCSBRUB",
                    "TO": "ZEC",
                    "FROMFEE": 0,
                    "TOFEE": 0.00003,
                    "IN": 3117.8,
                    "OUT": 1,
                    "AMOUNT": 101.59686579,
                    "MINAMOUNT": 5000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "ZEC",
                    "TO": "TCSBRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 2726.57,
                    "AMOUNT": 200000,
                    "MINAMOUNT": 3.56894381,
                    "MAXAMOUNT": 71.37887621,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TCSBRUB",
                    "TO": "ETH",
                    "FROMFEE": 0,
                    "TOFEE": 0.00068333,
                    "IN": 129477.63,
                    "OUT": 1,
                    "AMOUNT": 2.44643695,
                    "MINAMOUNT": 5000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "ETH",
                    "TO": "TCSBRUB",
                    "FROMFEE": 0.00124242,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 113230.66,
                    "AMOUNT": 200000,
                    "MINAMOUNT": 0.08593962,
                    "MAXAMOUNT": 1.7187924,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TCSBRUB",
                    "TO": "XMR",
                    "FROMFEE": 0,
                    "TOFEE": 0.0001426,
                    "IN": 12526.74,
                    "OUT": 1,
                    "AMOUNT": 25.28659799,
                    "MINAMOUNT": 5000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "XMR",
                    "TO": "TCSBRUB",
                    "FROMFEE": 0.0002139,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 10954.88,
                    "AMOUNT": 200000,
                    "MINAMOUNT": 0.88827984,
                    "MAXAMOUNT": 17.76559674,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TCSBRUB",
                    "TO": "BNBBEP20",
                    "FROMFEE": 0,
                    "TOFEE": 0.000105,
                    "IN": 23672.33,
                    "OUT": 1,
                    "AMOUNT": 13.3809731,
                    "MINAMOUNT": 5000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BNBBEP20",
                    "TO": "TCSBRUB",
                    "FROMFEE": 0.0001575,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 20701.9,
                    "AMOUNT": 200000,
                    "MINAMOUNT": 0.47005329,
                    "MAXAMOUNT": 9.40106582,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TCSBRUB",
                    "TO": "DOGE",
                    "FROMFEE": 0,
                    "TOFEE": 0.04104,
                    "IN": 6.1,
                    "OUT": 1,
                    "AMOUNT": 51845.18851934,
                    "MINAMOUNT": 5000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "DOGE",
                    "TO": "TCSBRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 5.34,
                    "AMOUNT": 200000,
                    "MINAMOUNT": 1821.24284283,
                    "MAXAMOUNT": 36424.85685668,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TCSBRUB",
                    "TO": "TRX",
                    "FROMFEE": 0,
                    "TOFEE": 1.5,
                    "IN": 5.51,
                    "OUT": 1,
                    "AMOUNT": 57412.45704956,
                    "MINAMOUNT": 5000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TRX",
                    "TO": "TCSBRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 4.82,
                    "AMOUNT": 200000,
                    "MINAMOUNT": 2016.81254283,
                    "MAXAMOUNT": 40336.25085654,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TCSBRUB",
                    "TO": "BUSD",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 82.77,
                    "OUT": 1,
                    "AMOUNT": 3826.84962343,
                    "MINAMOUNT": 23322,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BUSD",
                    "TO": "TCSBRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 72.38,
                    "AMOUNT": 200000,
                    "MINAMOUNT": 300,
                    "MAXAMOUNT": 2688.6284673,
                    "PARAM": "manual"
                },
                {
                    "FROM": "QWRUB",
                    "TO": "BTC",
                    "FROMFEE": 0,
                    "TOFEE": 0.00018655,
                    "IN": 191646150.61,
                    "OUT": 100,
                    "AMOUNT": 0.01395412,
                    "MINAMOUNT": 1000,
                    "MAXAMOUNT": 25278.89,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BTC",
                    "TO": "QWRUB",
                    "FROMFEE": 0.00001,
                    "TOFEE": 0,
                    "IN": 20,
                    "OUT": 32215762.73,
                    "AMOUNT": 289900,
                    "MINAMOUNT": 0.00030051,
                    "MAXAMOUNT": 0.09015152,
                    "PARAM": "manual"
                },
                {
                    "FROM": "QWRUB",
                    "TO": "USDTTRC20",
                    "FROMFEE": 0,
                    "TOFEE": 2.756705,
                    "IN": 82652351.72,
                    "OUT": 1000000,
                    "AMOUNT": 323.55446846,
                    "MINAMOUNT": 23322,
                    "MAXAMOUNT": 25278.89,
                    "PARAM": "manual"
                },
                {
                    "FROM": "USDTTRC20",
                    "TO": "QWRUB",
                    "FROMFEE": 4.694508,
                    "TOFEE": 0,
                    "IN": 1000000,
                    "OUT": 74883793.52,
                    "AMOUNT": 289900,
                    "MINAMOUNT": 300,
                    "MAXAMOUNT": 1939.20464168,
                    "PARAM": "manual"
                },
                {
                    "FROM": "QWRUB",
                    "TO": "LTC",
                    "FROMFEE": 0,
                    "TOFEE": 0.0000332,
                    "IN": 7345.79,
                    "OUT": 1,
                    "AMOUNT": 3.64052232,
                    "MINAMOUNT": 1000,
                    "MAXAMOUNT": 25278.89,
                    "PARAM": "manual"
                },
                {
                    "FROM": "LTC",
                    "TO": "QWRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 6174.15,
                    "AMOUNT": 289900,
                    "MINAMOUNT": 0.07839944,
                    "MAXAMOUNT": 23.5198332,
                    "PARAM": "manual"
                },
                {
                    "FROM": "QWRUB",
                    "TO": "DASH",
                    "FROMFEE": 0,
                    "TOFEE": 0.00000372,
                    "IN": 5237.68,
                    "OUT": 1,
                    "AMOUNT": 5.10578926,
                    "MINAMOUNT": 1000,
                    "MAXAMOUNT": 25278.89,
                    "PARAM": "manual"
                },
                {
                    "FROM": "DASH",
                    "TO": "QWRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 4402.28,
                    "AMOUNT": 289900,
                    "MINAMOUNT": 0.10995429,
                    "MAXAMOUNT": 32.98628637,
                    "PARAM": "manual"
                },
                {
                    "FROM": "QWRUB",
                    "TO": "ZEC",
                    "FROMFEE": 0,
                    "TOFEE": 0.00003,
                    "IN": 3227.32,
                    "OUT": 1,
                    "AMOUNT": 8.28629574,
                    "MINAMOUNT": 1000,
                    "MAXAMOUNT": 25278.89,
                    "PARAM": "manual"
                },
                {
                    "FROM": "ZEC",
                    "TO": "QWRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 2712.56,
                    "AMOUNT": 289900,
                    "MINAMOUNT": 0.17844719,
                    "MAXAMOUNT": 53.53415716,
                    "PARAM": "manual"
                },
                {
                    "FROM": "QWRUB",
                    "TO": "ETH",
                    "FROMFEE": 0,
                    "TOFEE": 0.00068333,
                    "IN": 134025.81,
                    "OUT": 1,
                    "AMOUNT": 0.19953273,
                    "MINAMOUNT": 1000,
                    "MAXAMOUNT": 25278.89,
                    "PARAM": "manual"
                },
                {
                    "FROM": "ETH",
                    "TO": "QWRUB",
                    "FROMFEE": 0.00124242,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 112648.85,
                    "AMOUNT": 289900,
                    "MINAMOUNT": 0.00429698,
                    "MAXAMOUNT": 1.2890943,
                    "PARAM": "manual"
                },
                {
                    "FROM": "QWRUB",
                    "TO": "XMR",
                    "FROMFEE": 0,
                    "TOFEE": 0.0001426,
                    "IN": 12966.77,
                    "OUT": 1,
                    "AMOUNT": 2.06238871,
                    "MINAMOUNT": 1000,
                    "MAXAMOUNT": 25278.89,
                    "PARAM": "manual"
                },
                {
                    "FROM": "XMR",
                    "TO": "QWRUB",
                    "FROMFEE": 0.0002139,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 10898.59,
                    "AMOUNT": 289900,
                    "MINAMOUNT": 0.04441399,
                    "MAXAMOUNT": 13.32419756,
                    "PARAM": "manual"
                },
                {
                    "FROM": "QWRUB",
                    "TO": "BNBBEP20",
                    "FROMFEE": 0,
                    "TOFEE": 0.000105,
                    "IN": 24503.87,
                    "OUT": 1,
                    "AMOUNT": 1.09135946,
                    "MINAMOUNT": 1000,
                    "MAXAMOUNT": 25278.89,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BNBBEP20",
                    "TO": "QWRUB",
                    "FROMFEE": 0.0001575,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 20595.53,
                    "AMOUNT": 289900,
                    "MINAMOUNT": 0.02350266,
                    "MAXAMOUNT": 7.05079936,
                    "PARAM": "manual"
                },
                {
                    "FROM": "QWRUB",
                    "TO": "DOGE",
                    "FROMFEE": 0,
                    "TOFEE": 0.04104,
                    "IN": 6.32,
                    "OUT": 1,
                    "AMOUNT": 4228.52183157,
                    "MINAMOUNT": 1000,
                    "MAXAMOUNT": 25278.89,
                    "PARAM": "manual"
                },
                {
                    "FROM": "DOGE",
                    "TO": "QWRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 5.31,
                    "AMOUNT": 289900,
                    "MINAMOUNT": 91.06214214,
                    "MAXAMOUNT": 27318.64264251,
                    "PARAM": "manual"
                },
                {
                    "FROM": "QWRUB",
                    "TO": "TRX",
                    "FROMFEE": 0,
                    "TOFEE": 1.5,
                    "IN": 5.71,
                    "OUT": 1,
                    "AMOUNT": 4682.59128709,
                    "MINAMOUNT": 1000,
                    "MAXAMOUNT": 25278.89,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TRX",
                    "TO": "QWRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 4.8,
                    "AMOUNT": 289900,
                    "MINAMOUNT": 100.84062714,
                    "MAXAMOUNT": 30252.18814241,
                    "PARAM": "manual"
                },
                {
                    "FROM": "QWRUB",
                    "TO": "BUSD",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 85.68,
                    "OUT": 1,
                    "AMOUNT": 312.11994094,
                    "MINAMOUNT": 23322,
                    "MAXAMOUNT": 25278.89,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BUSD",
                    "TO": "QWRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 72.01,
                    "AMOUNT": 289900,
                    "MINAMOUNT": 300,
                    "MAXAMOUNT": 2016.47135047,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BTC",
                    "TO": "MWRUB",
                    "FROMFEE": 0.00001,
                    "TOFEE": 0,
                    "IN": 20,
                    "OUT": 32545208.09,
                    "AMOUNT": 10000,
                    "MINAMOUNT": 0.00030051,
                    "MAXAMOUNT": 0.0060101,
                    "PARAM": "manual"
                },
                {
                    "FROM": "USDTTRC20",
                    "TO": "MWRUB",
                    "FROMFEE": 4.694508,
                    "TOFEE": 0,
                    "IN": 1000000,
                    "OUT": 69616169.99,
                    "AMOUNT": 499700,
                    "MINAMOUNT": 300,
                    "MAXAMOUNT": 646.40154723,
                    "PARAM": "manual"
                },
                {
                    "FROM": "LTC",
                    "TO": "MWRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 6237.28,
                    "AMOUNT": 10000,
                    "MINAMOUNT": 0.07839944,
                    "MAXAMOUNT": 1.56798888,
                    "PARAM": "manual"
                },
                {
                    "FROM": "DASH",
                    "TO": "MWRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 4447.3,
                    "AMOUNT": 10000,
                    "MINAMOUNT": 0.10995429,
                    "MAXAMOUNT": 2.19908576,
                    "PARAM": "manual"
                },
                {
                    "FROM": "ZEC",
                    "TO": "MWRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 2740.3,
                    "AMOUNT": 10000,
                    "MINAMOUNT": 0.17844719,
                    "MAXAMOUNT": 3.56894381,
                    "PARAM": "manual"
                },
                {
                    "FROM": "ETH",
                    "TO": "MWRUB",
                    "FROMFEE": 0.00124242,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 113800.82,
                    "AMOUNT": 10000,
                    "MINAMOUNT": 0.00429698,
                    "MAXAMOUNT": 0.08593962,
                    "PARAM": "manual"
                },
                {
                    "FROM": "XMR",
                    "TO": "MWRUB",
                    "FROMFEE": 0.0002139,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 11010.04,
                    "AMOUNT": 10000,
                    "MINAMOUNT": 0.04441399,
                    "MAXAMOUNT": 0.88827984,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BNBBEP20",
                    "TO": "MWRUB",
                    "FROMFEE": 0.0001575,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 20806.15,
                    "AMOUNT": 10000,
                    "MINAMOUNT": 0.02350266,
                    "MAXAMOUNT": 0.47005329,
                    "PARAM": "manual"
                },
                {
                    "FROM": "DOGE",
                    "TO": "MWRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 5.36,
                    "AMOUNT": 10000,
                    "MINAMOUNT": 91.06214214,
                    "MAXAMOUNT": 1821.24284283,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TRX",
                    "TO": "MWRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 4.84,
                    "AMOUNT": 10000,
                    "MINAMOUNT": 100.84062714,
                    "MAXAMOUNT": 2016.81254283,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BUSD",
                    "TO": "MWRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 66.94,
                    "AMOUNT": 499700,
                    "MINAMOUNT": 300,
                    "MAXAMOUNT": 672.15711682,
                    "PARAM": "manual"
                },
                {
                    "FROM": "YAMRUB",
                    "TO": "BTC",
                    "FROMFEE": 0,
                    "TOFEE": 0.00018655,
                    "IN": 193656994.99,
                    "OUT": 100,
                    "AMOUNT": 0.13823285,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BTC",
                    "TO": "YAMRUB",
                    "FROMFEE": 0.00001,
                    "TOFEE": 0,
                    "IN": 20,
                    "OUT": 32561846.75,
                    "AMOUNT": 30000,
                    "MINAMOUNT": 0.00180303,
                    "MAXAMOUNT": 0.0180303,
                    "PARAM": "manual"
                },
                {
                    "FROM": "YAMRUB",
                    "TO": "USDTTRC20",
                    "FROMFEE": 0,
                    "TOFEE": 2.756705,
                    "IN": 83519580.29,
                    "OUT": 1000000,
                    "AMOUNT": 3205.20743338,
                    "MINAMOUNT": 23322,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "USDTTRC20",
                    "TO": "YAMRUB",
                    "FROMFEE": 4.694508,
                    "TOFEE": 0,
                    "IN": 1000000,
                    "OUT": 75688247.04,
                    "AMOUNT": 30000,
                    "MINAMOUNT": 300,
                    "MAXAMOUNT": 387.84092834,
                    "PARAM": "manual"
                },
                {
                    "FROM": "YAMRUB",
                    "TO": "LTC",
                    "FROMFEE": 0,
                    "TOFEE": 0.0000332,
                    "IN": 7422.87,
                    "OUT": 1,
                    "AMOUNT": 36.06387896,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "LTC",
                    "TO": "YAMRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 6240.47,
                    "AMOUNT": 30000,
                    "MINAMOUNT": 0.47039666,
                    "MAXAMOUNT": 4.70396664,
                    "PARAM": "manual"
                },
                {
                    "FROM": "YAMRUB",
                    "TO": "DASH",
                    "FROMFEE": 0,
                    "TOFEE": 0.00000372,
                    "IN": 5292.64,
                    "OUT": 1,
                    "AMOUNT": 50.57916138,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "DASH",
                    "TO": "YAMRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 4449.57,
                    "AMOUNT": 30000,
                    "MINAMOUNT": 0.65972573,
                    "MAXAMOUNT": 6.59725727,
                    "PARAM": "manual"
                },
                {
                    "FROM": "YAMRUB",
                    "TO": "ZEC",
                    "FROMFEE": 0,
                    "TOFEE": 0.00003,
                    "IN": 3261.18,
                    "OUT": 1,
                    "AMOUNT": 82.08601427,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "ZEC",
                    "TO": "YAMRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 2741.7,
                    "AMOUNT": 30000,
                    "MINAMOUNT": 1.07068314,
                    "MAXAMOUNT": 10.70683143,
                    "PARAM": "manual"
                },
                {
                    "FROM": "YAMRUB",
                    "TO": "ETH",
                    "FROMFEE": 0,
                    "TOFEE": 0.00068333,
                    "IN": 135432.08,
                    "OUT": 1,
                    "AMOUNT": 1.97661864,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "ETH",
                    "TO": "YAMRUB",
                    "FROMFEE": 0.00124242,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 113859,
                    "AMOUNT": 30000,
                    "MINAMOUNT": 0.02578189,
                    "MAXAMOUNT": 0.25781886,
                    "PARAM": "manual"
                },
                {
                    "FROM": "YAMRUB",
                    "TO": "XMR",
                    "FROMFEE": 0,
                    "TOFEE": 0.0001426,
                    "IN": 13102.83,
                    "OUT": 1,
                    "AMOUNT": 20.43051257,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "XMR",
                    "TO": "YAMRUB",
                    "FROMFEE": 0.0002139,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 11015.67,
                    "AMOUNT": 30000,
                    "MINAMOUNT": 0.26648395,
                    "MAXAMOUNT": 2.66483951,
                    "PARAM": "manual"
                },
                {
                    "FROM": "YAMRUB",
                    "TO": "BNBBEP20",
                    "FROMFEE": 0,
                    "TOFEE": 0.000105,
                    "IN": 24760.98,
                    "OUT": 1,
                    "AMOUNT": 10.81126608,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BNBBEP20",
                    "TO": "YAMRUB",
                    "FROMFEE": 0.0001575,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 20816.78,
                    "AMOUNT": 30000,
                    "MINAMOUNT": 0.14101599,
                    "MAXAMOUNT": 1.41015987,
                    "PARAM": "manual"
                },
                {
                    "FROM": "YAMRUB",
                    "TO": "DOGE",
                    "FROMFEE": 0,
                    "TOFEE": 0.04104,
                    "IN": 6.39,
                    "OUT": 1,
                    "AMOUNT": 41888.74185921,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "DOGE",
                    "TO": "YAMRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 5.37,
                    "AMOUNT": 30000,
                    "MINAMOUNT": 546.37285285,
                    "MAXAMOUNT": 5463.7285285,
                    "PARAM": "manual"
                },
                {
                    "FROM": "YAMRUB",
                    "TO": "TRX",
                    "FROMFEE": 0,
                    "TOFEE": 1.5,
                    "IN": 5.77,
                    "OUT": 1,
                    "AMOUNT": 46386.86176162,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TRX",
                    "TO": "YAMRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 4.85,
                    "AMOUNT": 30000,
                    "MINAMOUNT": 605.04376285,
                    "MAXAMOUNT": 6050.43762848,
                    "PARAM": "manual"
                },
                {
                    "FROM": "YAMRUB",
                    "TO": "BUSD",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 86.57,
                    "OUT": 1,
                    "AMOUNT": 3091.93428721,
                    "MINAMOUNT": 23322,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BUSD",
                    "TO": "YAMRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 72.78,
                    "AMOUNT": 30000,
                    "MINAMOUNT": 300,
                    "MAXAMOUNT": 403.29427009,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBPRUB",
                    "TO": "BTC",
                    "FROMFEE": 0,
                    "TOFEE": 0.00018655,
                    "IN": 184019434.53,
                    "OUT": 100,
                    "AMOUNT": 0.17108912,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BTC",
                    "TO": "SBPRUB",
                    "FROMFEE": 0.00001,
                    "TOFEE": 0,
                    "IN": 20,
                    "OUT": 32558519.01,
                    "AMOUNT": 292000,
                    "MINAMOUNT": 0.00060101,
                    "MAXAMOUNT": 0.06010101,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBPRUB",
                    "TO": "USDTTRC20",
                    "FROMFEE": 0,
                    "TOFEE": 2.756705,
                    "IN": 79363133.45,
                    "OUT": 1000000,
                    "AMOUNT": 3967.04642468,
                    "MINAMOUNT": 23322,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "USDTTRC20",
                    "TO": "SBPRUB",
                    "FROMFEE": 4.694508,
                    "TOFEE": 0,
                    "IN": 1000000,
                    "OUT": 75680511.91,
                    "AMOUNT": 292000,
                    "MINAMOUNT": 300,
                    "MAXAMOUNT": 1292.80309445,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBPRUB",
                    "TO": "LTC",
                    "FROMFEE": 0,
                    "TOFEE": 0.0000332,
                    "IN": 7053.46,
                    "OUT": 1,
                    "AMOUNT": 44.63582624,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "LTC",
                    "TO": "SBPRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 6239.84,
                    "AMOUNT": 292000,
                    "MINAMOUNT": 0.15679889,
                    "MAXAMOUNT": 15.6798888,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBPRUB",
                    "TO": "DASH",
                    "FROMFEE": 0,
                    "TOFEE": 0.00000372,
                    "IN": 5029.25,
                    "OUT": 1,
                    "AMOUNT": 62.60121551,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "DASH",
                    "TO": "SBPRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 4449.12,
                    "AMOUNT": 292000,
                    "MINAMOUNT": 0.21990858,
                    "MAXAMOUNT": 21.99085758,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBPRUB",
                    "TO": "ZEC",
                    "FROMFEE": 0,
                    "TOFEE": 0.00003,
                    "IN": 3098.88,
                    "OUT": 1,
                    "AMOUNT": 101.59686579,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "ZEC",
                    "TO": "SBPRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 2741.42,
                    "AMOUNT": 292000,
                    "MINAMOUNT": 0.35689438,
                    "MAXAMOUNT": 35.68943811,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBPRUB",
                    "TO": "ETH",
                    "FROMFEE": 0,
                    "TOFEE": 0.00068333,
                    "IN": 128692.15,
                    "OUT": 1,
                    "AMOUNT": 2.44643695,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "ETH",
                    "TO": "SBPRUB",
                    "FROMFEE": 0.00124242,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 113847.37,
                    "AMOUNT": 292000,
                    "MINAMOUNT": 0.00859396,
                    "MAXAMOUNT": 0.8593962,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBPRUB",
                    "TO": "XMR",
                    "FROMFEE": 0,
                    "TOFEE": 0.0001426,
                    "IN": 12450.75,
                    "OUT": 1,
                    "AMOUNT": 25.28659799,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "XMR",
                    "TO": "SBPRUB",
                    "FROMFEE": 0.0002139,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 11014.54,
                    "AMOUNT": 292000,
                    "MINAMOUNT": 0.08882798,
                    "MAXAMOUNT": 8.88279837,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBPRUB",
                    "TO": "BNBBEP20",
                    "FROMFEE": 0,
                    "TOFEE": 0.000105,
                    "IN": 23528.72,
                    "OUT": 1,
                    "AMOUNT": 13.3809731,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BNBBEP20",
                    "TO": "SBPRUB",
                    "FROMFEE": 0.0001575,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 20814.66,
                    "AMOUNT": 292000,
                    "MINAMOUNT": 0.04700533,
                    "MAXAMOUNT": 4.70053291,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBPRUB",
                    "TO": "DOGE",
                    "FROMFEE": 0,
                    "TOFEE": 0.04104,
                    "IN": 6.07,
                    "OUT": 1,
                    "AMOUNT": 51845.18851934,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "DOGE",
                    "TO": "SBPRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 5.37,
                    "AMOUNT": 292000,
                    "MINAMOUNT": 182.12428428,
                    "MAXAMOUNT": 18212.42842834,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBPRUB",
                    "TO": "TRX",
                    "FROMFEE": 0,
                    "TOFEE": 1.5,
                    "IN": 5.48,
                    "OUT": 1,
                    "AMOUNT": 57412.45704956,
                    "MINAMOUNT": 2000,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "TRX",
                    "TO": "SBPRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 4.85,
                    "AMOUNT": 292000,
                    "MINAMOUNT": 201.68125428,
                    "MAXAMOUNT": 20168.12542827,
                    "PARAM": "manual"
                },
                {
                    "FROM": "SBPRUB",
                    "TO": "BUSD",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 82.27,
                    "OUT": 1,
                    "AMOUNT": 3826.84962343,
                    "MINAMOUNT": 23322,
                    "MAXAMOUNT": 150000,
                    "PARAM": "manual"
                },
                {
                    "FROM": "BUSD",
                    "TO": "SBPRUB",
                    "FROMFEE": 0,
                    "TOFEE": 0,
                    "IN": 1,
                    "OUT": 72.78,
                    "AMOUNT": 292000,
                    "MINAMOUNT": 300,
                    "MAXAMOUNT": 1344.31423365,
                    "PARAM": "manual"
                }
            ]
        }
    }
